---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: cook_ubnt-m-xw
    pull: default
    image: josmo/nyc-mesh-cooker
    commands:
      - ./cooker -c ar71xx/generic --profile=ubnt-nano-m-xw --flavor=lime_default --community=nycmesh.net/common-qmp-compat
    environment:
      J: 6

  - name: cook_ubnt-m-xm
    pull: default
    image: josmo/nyc-mesh-cooker
    commands:
      - ./cooker -c ar71xx/generic --profile=ubnt-nano-m --flavor=lime_default --community=nycmesh.net/common-qmp-compat
    environment:
      J: 6

  - name: cook_dir-869
    pull: default
    image: josmo/nyc-mesh-cooker
    commands:
      - ./cooker -c ar71xx/generic --profile=dir-869-a1 --flavor=lime_default --community=nycmesh.net/common-qmp-compat
    environment:
      J: 6

  - name: tar_artifacts
    pull: default
    image: josmo/nyc-mesh-cooker
    commands:
      - "tar --exclude='*vmlinux*' --exclude='*manifest' --exclude='*squashfs' --exclude='*lzma.bin' -cvzf ubnt-nano-m-xw-$DRONE_TAG.tar.gz -C output/ar71xx/generic/ubnt-nano-m-xw/lime_default ."
      - "tar --exclude='*vmlinux*' --exclude='*manifest' --exclude='*squashfs' --exclude='*lzma.bin' -cvzf ubnt-nano-m-xm-$DRONE_TAG.tar.gz -C output/ar71xx/generic/ubnt-nano-m/lime_default ."
      - "tar --exclude='*vmlinux*' --exclude='*manifest' --exclude='*squashfs' --exclude='*lzma.bin' -cvzf dir-869-a1-$DRONE_TAG.tar.gz -C output/ar71xx/generic/dir-869-a1/lime_default ."
    when:
      event:
        - tag

  - name: publish_images
    pull: default
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      checksum:
        - md5
        - sha1
        - sha256
      draft: true
      files: "./*.tar.gz"
    when:
      event:
        - tag

